### ISSUE TITLE
Running Resusability example

### ISSUE THREAD

**Issue by laitang2000** [ServiceStack/ServiceStack.UseCases#8]
Hi I have complied and attempting to run the example Reusability.
I get the following redis exception. Do I need to allow some firewall setting? Do I need to install Redis?

Thanks

{ServiceStack.Redis.RedisException: localhost:6379 ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:6379
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at ServiceStack.Redis.RedisNativeClient.Connect()
   at ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded()
   at ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   at ServiceStack.Redis.RedisNativeClient.AssertServerVersionNumber()
   at ServiceStack.Redis.RedisClient.GetServerRole()
   at ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
   at ServiceStack.Redis.RedisResolver.CreateMasterClient(Int32 desiredIndex)
   at ServiceStack.Redis.PooledRedisClientManager.GetClient()
   at ServiceStack.Redis.RedisClientsManagerExtensions.Exec(IRedisClientsManager redisManager, Action`1 lambda)
   at Reusability.AppHost.ResetAll(Container container, OrmLiteAuthRepository authRepo) in C:\Users\lai.tang\Downloads\ServiceStack.UseCases-master\ServiceStack.UseCases-master\Reusability\Global.asax.cs:line 90
   at Reusability.AppHost.Configure(Container container) in C:\Users\lai.tang\Downloads\ServiceStack.UseCases-master\ServiceStack.UseCases-master\Reusability\Global.asax.cs:line 78
   at ServiceStack.ServiceStackHost.Init()
   at Reusability.Global.Application_Start(Object sender, EventArgs e) in C:\Users\lai.tang\Downloads\ServiceStack.UseCases-master\ServiceStack.UseCases-master\Reusability\Global.asax.cs:line 98}

**Comment by mythz** [comment]
Yes it needs a local install of Redis running on `localhost:6379` which is the default for Redis.

You can download Redis for windows at: https://github.com/ServiceStack/redis-windows

**Comment by laitang2000** [comment]
Thanks!
